---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
  replicas: 1
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - name: wordpress
          image: wordpress@sha256:d0e8fb8de617c2949bffb473c5f515869255003b53e86333c5a91a5cdc883996

          ports:
            - containerPort: 80
