---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
  replicas: 1
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - name: wordpress
          image: wordpress@sha256:3319db8b6d9640f987df1aa4164b3e2f7ace0632be354791a2cb8c320ea723a7

          ports:
            - containerPort: 80
