image:
  repository: bitnamicharts/mysql
  version: 12.3.0
persistence:
  enabled: true
  storageClass: longhorn
  size: 10Gi
architecture: replication
auth:
  existingSecret: mysql-secret
primary:
  replicaCount: 1
